meta-imx: Mask vulkan-samples_git.bbappend
Issue: LIN1024-4318

vulkan-samples is not currently used. Therefore,
Mask vulkan-samples_git.bbappend otherwise the
following error will appear:

TOPDIR/tmp-glibc/work/armv7at2hf-neon-wrsmllib32-linux-gnueabi/lib32-vulkan-samples/git/git/framework/hpp_gui.h: In member function 'void vkb::HPPGui::prepare(vk::PipelineCache, vk::RenderPass, const std::vector<vk::PipelineShaderStageCreateInfo>&)':
TOPDIR/tmp-glibc/work/armv7at2hf-neon-wrsmllib32-linux-gnueabi/lib32-vulkan-samples/git/git/framework/hpp_gui.h:88:30: error: cannot convert 'const vk::PipelineCache' to 'VkPipelineCache' {aka 'long long unsigned int'}
   88 |                 Gui::prepare(pipeline_cache, render_pass, pssci);

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>