meta-imx: Put MACHINE_EXTRA_RRECOMMENDS in the imx-base-extend.inc file
Issue: LIN1024-3337

Fix test_signatures error, put MACHINE_EXTRA_RRECOMMENDS
in the imx-base-extend.inc file to avoid this mistake

INFO: FAIL: test_signatures (common.CommonCheckLayer.test_signatures)
INFO: ----------------------------------------------------------------------
INFO: Traceback (most recent call last):
self.fail('Adding layer %s changed signatures.\n%s' % (self.tc.layer['name'], msg))
AssertionError: Adding layer meta-imx-bsp changed signatures.
7 signatures changed, initial differences (first hash before, second after):
packagegroup-base:do_package: 46e93131bf6d8dd8aeabaf52a1c8c84e101abc1e098cfb3cc545739618f37934 -> 979330fa7b030166544f9820ed7f371f2debd563156b42371ef96c8e3b4b216c
bitbake-diffsigs --task packagegroup-base do_package --signature 46e93131bf6d8dd8aeabaf52a1c8c84e101abc1e098cfb3cc545739618f37934 979330fa7b030166544f9820ed7f371f2debd563156b42371ef96c8e3b4b216c
NOTE: Starting bitbake server...
basehash changed from 61c6148d0c8aa0f69a7df414373a82e42d4a979886536b3d95fccc59b737bb27 to 2e8123b5b7ee7e958422b1be753b2fe27d9c6f237232632620b069074c37939d
Variable MACHINE_EXTRA_RRECOMMENDS value changed:
@@ -1 +1,6 @@
-kernel-module-snd-ens1370 kernel-module-snd-rawmidi
+kernel-module-snd-ens1370 kernel-module-snd-rawmidi ${@bb.utils.contains('MACHINE_FEATURES', 'dpdk', 'kernel-module-dpdk-extras', '', d)} ${@bb.utils.contains('MACHINE_FEATURES', 'nxpiw416-sdio', 'nxp-wlan-sdk', '', d)} ${@bb.utils.contains('MACHINE_FEATURES', 'nxpiw612-sdio', 'nxp-wlan-sdk', '', d)} ${@bb.utils.contains('MACHINE_FEATURES', 'nxpwifi-all-sdio', 'nxp-wlan-sdk kernel-module-nxp-wlan', '', d)} ${@bb.utils.contains('MACHINE_FEATURES', 'nxpwifi-all-pcie', 'nxp-wlan-sdk kernel-module-nxp-wlan', '', d)}
+MACHINE_FEATURES{dpdk} = Unset
+MACHINE_FEATURES{nxpiw416-sdio} = Unset
+MACHINE_FEATURES{nxpiw612-sdio} = Unset
+MACHINE_FEATURES{nxpwifi-all-pcie} = Unset
+MACHINE_FEATURES{nxpwifi-all-sdio} = Unset

Stdout:
Loaded 1930 entries from dependency cache.

(LOCAL REV: NOT UPSTREAM) - will send to upstream

Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>