meta-imx: add back x11 for gtk+3
Issue: LINUXEXEC-31355

The x11 is required for gtk+3, otherwise the vim (depended on gtk+3)
building will be error like below:

| make[2]: Leaving directory 'tmp-glibc/work/aarch64-wrs-linux/vim/9.1.0114/git/src/po'
| gui_gtk_x11.c:92:12: fatal error: gdk/gdkx.h: No such file or directory
|    92 | #  include <gdk/gdkx.h>
|       |            ^~~~~~~~~~~~
| compilation terminated.

(LOCAL REV: NOT UPSTREAM) -- Will send upstream later

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>